#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/oauth-gateway/.env"
FORCE="false"

usage() {
  cat <<'EOF'
Generate a production-ready oauth-gateway .env file.

Usage:
  scripts/generate-prod-env.sh [--force] [--out path]

Options:
  --force       overwrite the target file if it already exists
  --out path    write to a custom file path
  -h, --help    show this help

The script generates strong random values for:
  GATEWAY_TOKEN_KEYS
  OAUTH_TX_SECRET
  ORIGIN_ZTA_TOKEN, if you do not paste an existing value
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force)
      FORCE="true"
      shift
      ;;
    --out)
      if [[ $# -lt 2 ]]; then
        echo "error: --out requires a path" >&2
        exit 2
      fi
      OUT_FILE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown option $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -e "$OUT_FILE" && "$FORCE" != "true" ]]; then
  echo "error: $OUT_FILE already exists. Use --force to overwrite." >&2
  exit 1
fi

random_base64url() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr '+/' '-_' | tr -d '=\n'
  else
    head -c 32 /dev/urandom | base64 | tr '+/' '-_' | tr -d '=\n'
  fi
}

dotenv_value() {
  local value="$1"
  if [[ "$value" =~ ^[A-Za-z0-9_./:@%+=,\{\}\"-]+$ ]]; then
    printf '%s' "$value"
  else
    printf "'%s'" "${value//\'/\'\\\'\'}"
  fi
}

prompt() {
  local label="$1"
  local default="${2:-}"
  local value
  if [[ -n "$default" ]]; then
    read -r -p "$label [$default]: " value
    printf '%s' "${value:-$default}"
  else
    read -r -p "$label: " value
    printf '%s' "$value"
  fi
}

prompt_required() {
  local label="$1"
  local default="${2:-}"
  local value=""
  while [[ -z "$value" ]]; do
    value="$(prompt "$label" "$default")"
    if [[ -z "$value" ]]; then
      echo "  required"
    fi
  done
  printf '%s' "$value"
}

echo "Generating production env for oauth-gateway"
echo

KVDB_BASE_URL="$(prompt_required "HTTPKVDB base URL" "https://kvdb-api.example.com")"
KVDB_API_KEY="$(prompt_required "Gateway read-only KVDB API key")"
GATEWAY_TOKEN_ACTIVE_KID="$(prompt_required "Gateway token active kid" "v1")"
GATEWAY_TOKEN_KEY="$(random_base64url)"
OAUTH_TX_SECRET="$(random_base64url)"
GATEWAY_COOKIE_NAME="$(prompt_required "Gateway cookie name" "df_oauth_token")"
DEFAULT_ORIGIN_TOKEN="$(random_base64url)"
ORIGIN_ZTA_TOKEN="$(prompt "Origin X-ZTA-Token value, blank to generate" "$DEFAULT_ORIGIN_TOKEN")"
OAUTH_ISSUER_URL="$(prompt_required "OAuth/OIDC issuer URL" "https://api.dreamreflex.com")"
OAUTH_DISCOVERY_URL="$(prompt "OAuth discovery URL, optional")"
OAUTH_CLIENT_ID="$(prompt_required "OAuth client id")"
OAUTH_CLIENT_AUTH_METHOD="$(prompt_required "OAuth client auth method" "client_secret_post")"
if [[ "$OAUTH_CLIENT_AUTH_METHOD" == "none" ]]; then
  OAUTH_CLIENT_SECRET="$(prompt "OAuth client secret, optional for public client")"
else
  OAUTH_CLIENT_SECRET="$(prompt_required "OAuth client secret")"
fi
OAUTH_SCOPES="$(prompt_required "OAuth scopes" "openid,email")"
ALLOW_PRIVATE_ORIGIN_IPS="$(prompt_required "Allow private origin IPs" "false")"
DOMAIN_CACHE_TTL_SECONDS="$(prompt_required "Domain config cache TTL seconds" "60")"
ORIGIN_CACHE_TTL_SECONDS="$(prompt_required "Origin config cache TTL seconds" "60")"
ACCESS_CACHE_TTL_SECONDS="$(prompt_required "Access/user cache TTL seconds" "30")"
OAUTH_DISCOVERY_CACHE_TTL_SECONDS="$(prompt_required "OAuth discovery cache TTL seconds" "300")"

mkdir -p "$(dirname "$OUT_FILE")"
umask 077

{
  echo "# Generated by scripts/generate-prod-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "# HTTPKVDB userspace is fixed in code as ztafirewall."
  echo "KVDB_BASE_URL=$(dotenv_value "$KVDB_BASE_URL")"
  echo "KVDB_API_KEY=$(dotenv_value "$KVDB_API_KEY")"
  echo "GATEWAY_TOKEN_ACTIVE_KID=$(dotenv_value "$GATEWAY_TOKEN_ACTIVE_KID")"
  echo "GATEWAY_TOKEN_KEYS=$(dotenv_value "{\"$GATEWAY_TOKEN_ACTIVE_KID\":\"$GATEWAY_TOKEN_KEY\"}")"
  echo "OAUTH_TX_SECRET=$(dotenv_value "$OAUTH_TX_SECRET")"
  echo "GATEWAY_COOKIE_NAME=$(dotenv_value "$GATEWAY_COOKIE_NAME")"
  echo "ORIGIN_ZTA_TOKEN=$(dotenv_value "$ORIGIN_ZTA_TOKEN")"
  echo "OAUTH_ISSUER_URL=$(dotenv_value "$OAUTH_ISSUER_URL")"
  if [[ -n "$OAUTH_DISCOVERY_URL" ]]; then
    echo "OAUTH_DISCOVERY_URL=$(dotenv_value "$OAUTH_DISCOVERY_URL")"
  else
    echo "# OAUTH_DISCOVERY_URL="
  fi
  echo "OAUTH_CLIENT_ID=$(dotenv_value "$OAUTH_CLIENT_ID")"
  echo "OAUTH_CLIENT_SECRET=$(dotenv_value "$OAUTH_CLIENT_SECRET")"
  echo "OAUTH_SCOPES=$(dotenv_value "$OAUTH_SCOPES")"
  echo "OAUTH_CLIENT_AUTH_METHOD=$(dotenv_value "$OAUTH_CLIENT_AUTH_METHOD")"
  echo "ALLOW_PRIVATE_ORIGIN_IPS=$(dotenv_value "$ALLOW_PRIVATE_ORIGIN_IPS")"
  echo "DOMAIN_CACHE_TTL_SECONDS=$(dotenv_value "$DOMAIN_CACHE_TTL_SECONDS")"
  echo "ORIGIN_CACHE_TTL_SECONDS=$(dotenv_value "$ORIGIN_CACHE_TTL_SECONDS")"
  echo "ACCESS_CACHE_TTL_SECONDS=$(dotenv_value "$ACCESS_CACHE_TTL_SECONDS")"
  echo "OAUTH_DISCOVERY_CACHE_TTL_SECONDS=$(dotenv_value "$OAUTH_DISCOVERY_CACHE_TTL_SECONDS")"
} > "$OUT_FILE"

chmod 600 "$OUT_FILE" 2>/dev/null || true

echo
echo "Wrote $OUT_FILE"
echo "File mode set to 600 where supported."
echo
echo "Next steps:"
echo "  1. Copy these values into the EdgeOne production environment."
echo "  2. Keep GATEWAY_TOKEN_KEYS and OAUTH_TX_SECRET in a secret manager."
echo "  3. Do not commit $OUT_FILE."
